### ISSUE TITLE
dj.internal.Master/getParts throws error in MATLAB 2016a or earlier

### ISSUE THREAD

**Issue by jakereimer** [datajoint/datajoint-matlab#107]
`getParts(schema.Table)`  throws error:
`Undefined function 'startsWith' for input arguments of type
'cell'.`

`startsWith` was not introduced until 2016b:
[doc page](https://www.mathworks.com/help/matlab/ref/startswith.html)

**Comment by eywalker** [comment]
Issued fixed by #108
