### ISSUE TITLE
Support for offline data analysis by DB replication ?

### ISSUE THREAD

**Issue by ragavsathish** [datajoint/datajoint-matlab#111]
Feature Summary:  Support for offline data analysis by database replication. Will it be good to use SymmetricDS + MySQL docker container  for database replication and synchronization (so that user can  “check out” a portion/schema of the main MYSQL DB and work with it locally, offline)

Description: Recently I have been playing around with data joint and it works great because of ORM mapping and simplified query interface. However, It would be more beneficial if there is support for offline data access and background data synchronization. In my understanding, I see most of the electrophysiology analysis involves single user based CRUD operations (not much of multi user transactional database). Hence, creating per user based database on the user machine and synchronizing it with the whole lab database would be more beneficial. 

Requesting contributors opinion on it!
Reference: https://www.symmetricds.org/

Thanks,
Sathish

**Comment by dimitri-yatsenko** [comment]
Thank you, @ragavsathish.  Do you suggest this as a feature of the DataJoint client in MATLAB or do you see this as part of the overall process.   What features would be needed to make this type of replication easier?

**Comment by dimitri-yatsenko** [comment]
I am closing this because this is not a DataJoint feature.  Data synchronization can be done by a number of third-party tools.
