### ISSUE TITLE
Prevent dropping part tables directly (without override flag)

### ISSUE THREAD

**Issue by austin-hilberg** [datajoint/datajoint-matlab#125]
According to the DataJoint model's guarantee of group integrity, part tables should only dropped as part of dropping their master.
Currently there is no mechanism preventing this in DataJoint MATLAB.
DataJoint Python only allows dropping of part tables when using a `force=True` flag.

**Comment by ixcat** [comment]
-> https://github.com/datajoint/datajoint-matlab/issues/126
