### ISSUE TITLE
Implement configurable external storage

### ISSUE THREAD

**Issue by austin-hilberg** [datajoint/datajoint-matlab#143]

**Comment by dimitri-yatsenko** [comment]
Planhttps://github.com/datajoint/mym/pull/10

**Comment by shenshan** [comment]
Decisions:
2. Configuration
- potential retirement of `dj.set`, 
- configure with `dj_local_conf.json`, 
- inherit from mapping object?
- global and local config: order of default, global, local, env?
3. check the availability of uuid support from MATLAB
https://www.mathworks.com/matlabcentral/answers/240447-using-java-uuid-in-matlab#answer_191523
If too hard, we can skip the support of uuid.
