### ISSUE TITLE
In the branch external-storage, the Declare complains about comment with some characters.

### ISSUE THREAD

**Issue by shenshan** [datajoint/datajoint-matlab#210]
Here is the error:
```
Error using dj.internal.Declare.compileAttribute (line 348)
illegal characters in attribute comment "code version of the stimulus, usually two numbers "maze_version=2.1, code_version = 4.0". In the future: a githash?"
```
I tried removing the : as well, but still got the same error.

**Comment by guzman-raphael** [comment]
Confirmed that this is an issue that exists on current release and `master`. The issue is the `"` which you may substitute safely with `'` until it can be addressed.
