### ISSUE TITLE
mym/caching_sha2_password version check

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-matlab#249]
When https://github.com/datajoint/mym/issues/52 is released, mym version check should verify against that release to ensure mysql 8.x authentication compatibility

**Comment by ixcat** [comment]
^ unassigned on purpose

**Comment by guzman-raphael** [comment]
Pasting from Slack:
Raphael  17 days ago
OK, I found it in the C Connector for MariaDB, could you give a try copying it into the PLUGIN_DIR?
https://mariadb.com/kb/en/mariadb-connector-c-319-release-notes/
MariaDB KnowledgeBaseMariaDB KnowledgeBase
MariaDB Connector/C 3.1.9 Release Notes
Status: Stable (GA) | Release Date: 24 Jun 2020
chris  17 days ago
thanks! - just copying the library in yields:

Setting up mym...
No connections open
mym is now ready for use.
Error using mym
Commands out of sync; you can't run this command nowError in dj.Connection/query (line 179)
                mym(self.connId, queryStr, v{:});Error in dj.conn (line 112)
        query(connObj, 'status')

(did matlab restart to be sure)but thinking maybe combining the two libraries (regular connector provided in mym + caching_sha2 from another connector install) might be related. If there are build instructions handy can try a full mym build against the mariadb connector install (and/or the libraries installed as ‘base’ with my percona install)

**Comment by guzman-raphael** [comment]
Closing due to PR #285
