### ISSUE TITLE
Better handling of Ctrl-C in del() and parpopulate() calls

### ISSUE THREAD

**Issue by ahoenselaar** [datajoint/datajoint-matlab#29]
Hitting Ctrl-C while `del`, `parpopulate`, or any other function that starts a transaction are executing will leave the user "trapped" inside of this transaction.
Given that InnoDB enforces isolation, this can cause highly unexpected behavior for the user, including the loss of inserted tuples and seemingly inconsistent query results.

Proposal:
Add a call to `cancelTransaction` via an `onCleanup` handler. Functions registered via `onCleanup` execute even in the case of Ctrl-C, whereas statements in a `catch` block do not.

**Comment by dimitri-yatsenko** [comment]
I think this is a "won't fix"

**Comment by eywalker** [comment]
Although the latter half of this thread's conversation centered around handling of `SIGINT` (as issued by `CTRL-C`) in MEX code, the issue stated by the opening question was addressed by #60. Either way, there is no obvious fix for handling of `CTRL-C` in MEX code so I'm closing this issue as resolved. Should we decide to work on the MEX code issue, we'll open a separate issue.
