### ISSUE TITLE
Matlab installation is not successful on Windows Matlab r2017a v9.2.0.538062

### ISSUE THREAD

**Issue by shenshan** [datajoint/datajoint-matlab#299]
A princeton user reported that the newest matlab installation procedure is not working for Windows Matlab r2017a

He thinks that DJ matlab does not handle the search path of mym correctly.
It should be `Home\MATLAB\Add-Ons\Toolboxes\mym\code\mym.m`

**Comment by guzman-raphael** [comment]
@shenshan Thanks for the report. We'll need more details to provide a good response. Can the user share the result of `path`?

**Comment by guzman-raphael** [comment]
It appears that MATLAB R2018b (**9.5**) is the first release where `code` is removed from the `Add-Ons/Toolbox` path (confirmed by manually checking releases from `R2016b`-`R2018b`). Therefore, should only need to update the following dependencies to resolve this issue:
- [mym](https://github.com/datajoint/mym/blob/ad7eeab9527b53623f0f0c0f6988f91d2a4b489f/mym.m#L13)
- [GHToolbox](https://github.com/datajoint/GHToolbox/blob/57a99396d3e141852413ace5fe2ac8c656c71586/%2Bghtb/uninstall.m#L20)
