### ISSUE TITLE
External table error - working with schema having existing external table (declared with datajoint-python)

### ISSUE THREAD

**Issue by ttngu207** [datajoint/datajoint-matlab#359]
## Bug Report
Accessing a table from a schema with existing external table (declared previously with datajoint-python) yields error:
```
Error using containers.Map/subsref
The specified key is not present in this container.
```

### Description
Related to this error is another error with matlab-datajoint trying to declare external table that already existed:

```
Error using mym
Table '~external_ephys_store' already exists
Error in dj.Connection/query (line 185)
                mym(self.connId, queryStr, v{:});
Error in dj.internal.ExternalTable/create (line 101)
            self.schema.conn.query(sql);
Error in dj.internal.Table/create (line 628)
                table.create;
Error in dj.internal.Table/get.plainTableName (line 116)
                self.create
Error in dj.internal.Table/get.tableHeader (line 83)
                self.tableHeader = self.schema.headers(self.plainTableName);
Error in dj.internal.GeneralRelvar/compile (line 676)
                    header = derive(tab.tableHeader);
Error in dj.internal.GeneralRelvar/get.header (line 43)
            header = self.compile;
Error in dj.internal.GeneralRelvar/get.primaryKey (line 51)
            names = self.header.primaryKey;
Error in dj.internal.AutoPopulate/populateSanityChecks (line 445)
                abovePopRel =
                setdiff(self.primaryKey(1:min(end,length(source.primaryKey))),
                source.primaryKey);
Error in dj.internal.AutoPopulate/parpopulate (line 188)
                rels{i}.populateSanityChecks
```

Following Raphael's suggestion, a fix was made [here](https://github.com/datajoint/datajoint-matlab/blob/755ea67c0d348ddbc4d84736e0412667ffa627da/%2Bdj/%2Binternal/Declare.m#L191), changing to:
```
create_sql = sprintf('CREATE TABLE IF NOT EXISTS `%s`.`%s` (\n', table_instance.schema.dbname,...
                tableName);
```

This fix seems to resolve the "table already exists" issue, but then accessing tables in this schema resulted in a new error (reported here), see below for full error stack.

### Reproducibility
Include:
- OS WIN
- MATLAB 2018b
- MySQL 5.7
- MySQL Deployment Strategy local-native
- DataJoint Version 3.4.2

- Complete error stack as a result of evaluating the above steps

```
>> analysis_m.AngularOccupancy

ans = 


Object analysis_m.AngularOccupancy

Error using containers.Map/subsref
The specified key is not present in this container.

Error in dj.internal.Table/get.plainTableName (line 117)
                self.plainTableName = self.schema.tableNames(self.className);

Error in dj.internal.Table/get.tableHeader (line 83)
                self.tableHeader = self.schema.headers(self.plainTableName);

Error in dj.internal.GeneralRelvar/compile (line 677)
                    header = derive(tab.tableHeader);

Error in dj.internal.GeneralRelvar/get.header (line 43)
            header = self.compile;

Error in dj.internal.GeneralRelvar/disp (line 73)
            hdr = self.header;
```

**Comment by guzman-raphael** [comment]
@ttngu207 Just wanted to capture the summary of our last discussion on this topic. This issue turned out to be due to user misuse when invoking `createSchema` (`package`, `parentdir`, and `db` variables were not being set properly).

However, there was an issue identified relating to loading a `dj.config` file as soon as MATLAB boots. For this case, the default values were not being pulled in appropriately. Treating the solution to this ladder issue as sufficient to close this GH issue.

**Comment by felixsmli** [comment]
> @ttngu207 Just wanted to capture the summary of our last discussion on this topic. This issue turned out to be due to user misuse when invoking `createSchema` (`package`, `parentdir`, and `db` variables were not being set properly).
> 
> However, there was an issue identified relating to loading a `dj.config` file as soon as MATLAB boots. For this case, the default values were not being pulled in appropriately. Treating the solution to this ladder issue as sufficient to close this GH issue.

Hello, I'm having the same problem. Can you be more specific what does "misuse when invoking createSchema (package, parentdir, and db variables were not being set properly)" mean? Thank you.

I'm trying to use raw external storage, here is the example.

I have a schema folder, `+schema1`, inside it a `getSchema.m`:

```MATLAB
   function obj = getSchema
   persistent schemaObject
   if isempty(schemaObject)
       schemaObject = dj.Schema(dj.conn, 'schema1', 'root_schema1');
   end
   obj = schemaObject;
   end
```

And a example table, `RawObject.m`:

```MATLAB
%{
# Test external storage for matlab objects
object_id            : int unsigned
-----
object               : blob@external_raw
%}

classdef RawObject < dj.Manual
end
```

In my script I try:

```MATLAB
insert(schema1.RawObject, struct('object_id', 1, 'object', rand(1000,1000)))
```

And get error:

Error using mym
Table '~external_external_raw' already exists

Error in dj.Connection/query (line 185)
                mym(self.connId, queryStr, v{:});

Error in dj.internal.ExternalTable/create (line 101)
            self.schema.conn.query(sql);

Error in dj.internal.Table/get.plainTableName (line 116)
                self.create

Error in dj.internal.Table/get.fullTableName (line 110)
            name = sprintf('`%s`.`%s`', self.schema.dbname, self.plainTableName);

Error in dj.internal.ExternalTable/upload_buffer (line 119)
                'DUPLICATE KEY UPDATE timestamp=CURRENT_TIMESTAMP'], self.fullTableName, ...

Error in dj.Relvar/insert/makePlaceholder (line 274)
                        value = self.schema.external.table(...

Error in dj.Relvar/insert (line 353)
                    [v, placeholder] = makePlaceholder(i, tuple.(header.attributes(i).name));

Error in test (line 32)
insert(schema1.RawObject, struct('object_id', 1, 'object', rand(1000,1000)))
