### ISSUE TITLE
bug with del()

### ISSUE THREAD

**Issue by arsenyf** [datajoint/datajoint-matlab#379]
When attempting to delete I get the following error:

>> del(EXP2.Session & 'subject_id=481102')
Error using  ~ 
Too many input arguments.

Error in dj.Relvar/del (line 95)
                            if ~fks.aliased

'subject_id' is the primary key for table EXP2.Session, and this always worked before. I noticed it after upgrading to DataJoint version 3.4.3. 
del() with few other tables that are under EXP2.Session with the same key that I tested worked fine

MATLAB 2018b
DataJoint version 3.4.3

<img width="1719" alt="bug" src="https://user-images.githubusercontent.com/31078965/124399973-2d483980-dced-11eb-9054-1a745aa961a8.png">

**Comment by kabilar** [comment]
@kabilar @alvalunasan

**Comment by Alvalunasan** [comment]
Do we have any updates on this ?
Our team here in Princeton has been facing this issue a lot now.
Thanks

**Comment by zfj1** [comment]
Just commenting here since this hasn't had any traction in a while. I believe this issue can be resolved with an edit to a single line of code, as in https://github.com/datajoint/datajoint-matlab/pull/380/commits/938626cb412c635770cc3912f59660e4e009cc61. This probably arose in the most recent release because of weak typing in MATLAB and testing against a table with only one foreign key. I haven't checked that the rest of the logic there is sound, but if you read the comments it's obvious this is what they were going for. So as a workaround before this gets formally addressed you should just be able to edit that line in your datajoint installation.

**Comment by Alvalunasan** [comment]
Example of an incorrect deletion on version 3.4.2
table **lab.DutyRoaster:** (lab.User  as foreign key many times)
```
%{
duty_roaster_date:  date       # date from which this assignment is valid.
----- 
(monday_duty)    -> lab.User(user_id)
(tuesday_duty)   -> lab.User(user_id)
(wednesday_duty) -> lab.User(user_id)
.
.
%}
```
**testtech_del1** is a reference **only** for **record 2   {'2021-03-11'}**
```
lab.DutyRoaster

    DUTY_ROASTER_DATE       monday_duty         tuesday_duty        wednesday_duty      ...   
    _________________    _________________    _________________    _________________    ...

     {'2021-03-10'}      {'jrw10'        }    {'baptista'     }    {'jrw10'        }    ...
     {'2021-03-11'}      {'testtech_del1'}    {'testtech_del2'}    {'testtech_del1'}    ...
```
We try to delete that user it tries to **delete all records from duty_roaster** : 
```
key.user_id = 'testtech_del1'
del(lab.User & key)

ABOUT TO DELETE:
       1 tuples from `u19_lab`.`user` (manual)
       2 tuples from `u19_lab`.`duty_roaster` (manual)
```

**Comment by kabilar** [comment]
Thanks @Alvalunasan.  I will add to your example below.  Below is Alvaro's example with DataJoint MATLAB version 3.4.3. 

## Schema diagram

![image](https://user-images.githubusercontent.com/871137/152626655-8f660634-b234-4048-b3d1-13a836752187.png)

## Table entries
```
lab.User()

     USER_ID     user_nickname    full_name       email         phone       mobile_carrier      slack       contact_via      presence       primary_tech    tech_responsibility    slack_webhook    watering_logs    day_cutoff_time
    _________    _____________    __________    __________    __________    ______________    __________    ___________    _____________    ____________    ___________________    _____________    _____________    _______________

    {'user0'}    {'nickname0'}    {0×0 char}    {0×0 char}    {0×0 char}       {'att'}        {0×0 char}     {'Slack'}     {'Available'}      {'N/A'}             {'N/A'}           {0×0 char}       {0×0 char}        {'=BLOB='}   
    {'user1'}    {'nickname1'}    {0×0 char}    {0×0 char}    {0×0 char}       {'att'}        {0×0 char}     {'Slack'}     {'Available'}      {'N/A'}             {'N/A'}           {0×0 char}       {0×0 char}        {'=BLOB='}   
    {'user2'}    {'nickname2'}    {0×0 char}    {0×0 char}    {0×0 char}       {'att'}        {0×0 char}     {'Slack'}     {'Available'}      {'N/A'}             {'N/A'}           {0×0 char}       {0×0 char}        {'=BLOB='}   
```


```
lab.DutyRoaster()

    DUTY_ROASTER_DATE    monday_duty    tuesday_duty    wednesday_duty    thursday_duty    friday_duty    saturday_duty    sunday_duty
    _________________    ___________    ____________    ______________    _____________    ___________    _____________    ___________

     {'2020-01-01'}       {'user0'}      {'user0'}        {'user0'}         {'user1'}       {'user1'}       {'user1'}       {'user1'} 
     {'2020-12-31'}       {'user1'}      {'user1'}        {'user2'}         {'user2'}       {'user2'}       {'user2'}       {'user2'} 
```
## Test case 1 with DataJoint MATLAB 3.4.2
### Versions
MATLAB R2020b
DataJoint MATLAB 3.4.2
mym 2.8.2

- Deleting `user0` in lab.User, deletes all entries in lab.DutyRoaster table.
```
key.user_id = 'user0'
del(lab.User & key)

ABOUT TO DELETE:
       1 tuples from `kabilar_lab`.`user` (manual)
       2 tuples from `kabilar_lab`.`duty_roaster` (manual)

Proceed to delete? (yes/no) > yes
Deleting from lab.DutyRoaster
Deleting from lab.User
committed


lab.DutyRoaster()
0 tuples
```

## Test case 2 with DataJoint MATLAB 3.4.3
### Versions
MATLAB R2020b
DataJoint MATLAB 3.4.3
mym 2.8.2

- Deleting `user0` in lab.User, throws an error.


```
key.user_id = 'user0'
del(lab.User & key)

key = 

  struct with fields:

    user_id: 'user0'

Error using  ~ 
Too many input arguments.

Error in dj.Relvar/del (line 95)
                            if ~fks.aliased
```
