### ISSUE TITLE
Default popRel

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-matlab#41]
The Python version of datajoint implements a default value for the populate relation, i.e. the product of the parent tables.  The majority of current DataJoint classes use this default.

I propose to replicate this feature in MATLAB.

**Comment by aecker** [comment]
I agree; this is a useful feature.

**Comment by dimitri-yatsenko** [comment]
Fixed in #72

**Comment by eywalker** [comment]
This feature was implemented in #72 and now merged into an official release `v3.0.0` in #83.
