### ISSUE TITLE
use the database toolbox instead of mym?

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-matlab#52]
Let's switch to using Mathworks' database toolbox.

Does anyone have any objections?  It's a quick change.  But please test that you can connect to your databases from all your platforms using the database toolbox.

**Comment by dimitri-yatsenko** [comment]
Do people have much experience with the database toolbox.  It seems like that's the standard way of accessing database from matlab.  It would seem that it would be the preferred way to go.  However, sometimes its queries freeze inexplicably and I wonder if it is less reliable than mym.

**Comment by eywalker** [comment]
I have used database toolbox on Matlab before (although this is now more than 3 years ago), and back then didn't have great experience with it. The connection was rather unreliable. Perhaps it's been improved and if it works well, I would think it is not a bad idea *for the newer releases of Matlab*. However, for the older releases of Matlab, I think the degree of unreliability will make `mYm` preferred solution.

**Comment by dimitri-yatsenko** [comment]
Okay, i have tested it too and it does not extremely well.  We will keep `mym`
