### ISSUE TITLE
No slashes displayed in path when updating class via addAttribute

### ISSUE THREAD

**Issue by jakereimer** [datajoint/datajoint-matlab#55]
`addAttribute(experiment.Stack,'filename : varchar(255) # file base name')`
`table updated`
`Update table declaration in C:workpipelinematlabschemas+experimentStack.m? (yes/no) > yes`
`updated table definition`

However, the class is indeed updated correctly.

**Comment by eywalker** [comment]
This is caused by not escaping the backslashes `\` originating from Windows path in the prompt string.
