### ISSUE TITLE
"Escape backslash in dj.ask" breaks string formatting.

### ISSUE THREAD

**Issue by mjlm** [datajoint/datajoint-matlab#57]
So I made pull request #56 recently to escape backslashes in dj.ask so that paths are correctly displayed. I didn't think this through enough, for which I apologize: Some other functions (e.g. dj.Schema/makeClass) pass strings with special characters (e.g. \n) to dj.ask. These get escaped-out as well now. I'm not sure what the best approach is. Damn Windows for using the backslash as a file separator, I guess.

**Comment by dimitri-yatsenko** [comment]
Yes, we need to implement unit tests for these exact types of problems.  `datajoint-matlab` is about to get a new wave of serious developments as a couple of groups are adopting it and have funding to support its development.

**Comment by dimitri-yatsenko** [comment]
I will be more careful accepting PRs.

**Comment by eywalker** [comment]
Escaping of `\` to `\\` should not happen blindly within `dj.ask`. The solution is to format the question string before passing in into the `dj.ask`, appropriately escaping backslashes if the question contains path. Which question (i.e. use of `dj.ask`) specifically involves paths?

**Comment by eywalker** [comment]
Also in Matlab, [as given here](https://www.mathworks.com/matlabcentral/answers/117110-dealing-with-and-windows-vs-unix-for-path-definition), you can actually go ahead and stick to using forward slashes `/` even when dealing with paths on Windows. That is, when you have to give paths to Matlab on Windows (e.g. `dir`), Matlab will be fine with either `C:\Users\MATLAB` or `C:/Users/MATLAB`, thus letting you totally avoid the backslashes `\` in the path problem.

**Comment by eywalker** [comment]
This is now fixed with #61.
