### ISSUE TITLE
Lock wait timeouts

### ISSUE THREAD

**Issue by aecker** [datajoint/datajoint-matlab#6]
I'm getting a lot of "lock wait timeout" errors these days when using the cluster to parpopulate tables (happens already with 16 workers but increasingly often with larger numbers). I already researched it quite a bit and it is related to InnoDB's row level locking but I don't understand yet what causes the lock. I posted a question on stackexchange as well: http://dba.stackexchange.com/questions/31611/innodb-row-level-locks-without-selects

I was wondering if anyone else has the same issue and/or any ideas what causes it or how to fix it.

**Comment by eywalker** [comment]
This issue needs more thorough coverage in Wiki with graphics to explain - it will be to much to ask the users to read through this issue and to understand.

**Comment by mjlm** [comment]
I agree with @eywalker ... I run into the timeouts a lot but I don't understand what the problem is and how to solve it.
