### ISSUE TITLE
Matlab floats need inf

### ISSUE THREAD

**Issue by wrongu** [datajoint/datajoint-matlab#70]

**Comment by dimitri-yatsenko** [comment]
Yes.  Unfortunately, MySQL does not support the full IEEE 754 standard for floats with its special values for NaN, -Inf, and +Inf.  We use NULL to stand for NaN but not sure what to do about the Infs.

**Comment by dimitri-yatsenko** [comment]
the problem is not specific to MySQL but to SQL in general.  It's one of its major flaws.  I am not sure what we can do other than document this deficiency.  Valid floats can be stored in blobs but then they cannot be used in searches and sorting.

**Comment by dimitri-yatsenko** [comment]
we could solve this in a very complicated way by adding an additional field to flag `+/- Inf` for every `float` or `double` field.

**Comment by dimitri-yatsenko** [comment]
I propose to simply document this deficiency and mark as a `won't fix`.

**Comment by eywalker** [comment]
I support the `wontfix` idea - just document how one could get around this problem by having another field that can be used to maintain `+/-Inf` should that be necessary.

**Comment by wrongu** [comment]
Thanks for looking into it!

**Comment by dimitri-yatsenko** [comment]
another solution is to reserve special values for `-Inf` and `+Inf`  The probability of hitting them by chance is 2^(-61) for doubles and 2^(-31) for single floats.
