### ISSUE TITLE
Support new MATLAB strings where character arrays are supported.

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-matlab#76]
MATLAB R2017a supports strings in the format "string".  DataJoint does not always interpret them as strings.

For example, in
```matlab
experiment.Scan & "animal_id=8628"
```
fails to restrict to the correct animal_id.

**Comment by dimitri-yatsenko** [comment]
fixed in 6f4e2e5c7 for restrictions but it may pop up in other cases.

**Comment by dimitri-yatsenko** [comment]
I have just realized that fixing this bug may make the program backward incompatible and `R2017a` or later will be required.  Are we okay with requiring R2017a or later?

**Comment by eywalker** [comment]
I don't think so - that's asking a lot for otherwise R2017a specific issue. How did you fix the issue with "strings", and why we could be backward incompatible?

**Comment by eywalker** [comment]
Besides, I don't think you were referring to the right commit with 6f4e2e5c7, as I don't see anything related to string handling there.

**Comment by dimitri-yatsenko** [comment]
It was in commit 74ba66fbd -- added the `isstring` test.  Actually, `isstring` was introduced in `R2016b`.

**Comment by dimitri-yatsenko** [comment]
strings were introduced in `R2016b` but the double quote syntax for them -- in `R2017a`.  I feel that restrictions should accept strings but there is not a really good way to make backward compatible to pre-R2016b.

**Comment by eywalker** [comment]
I think we ought to write a quick wrapper that check whether `isstring` is available and then use it. I'd hate to make Matlab require R2016b or above just for this.

**Comment by dimitri-yatsenko** [comment]
what's the downside of asking people to upgrade?  We  do a version check in `dj.Connection`.  Currently it requires `R2015a`, so it already asks people to upgrade.

**Comment by dimitri-yatsenko** [comment]
When we add regression tests, we can test multiple versions.  Now I only test on the latest.

**Comment by eywalker** [comment]
Matlab is not completely backward compatible with their version changes, and thus people often deliberately choose not to upgrade. Unless we see an obvious reason not to support an older version, I don't like the idea of just asking updates.

**Comment by eywalker** [comment]
How can you test on multiple version with regression tests? We still need to run it on multiple Matlab don't we?

**Comment by dimitri-yatsenko** [comment]
yep, multiple matlabs.  But I think, realistically, the regression tests will be for `R2017a+`

**Comment by dimitri-yatsenko** [comment]
fixed this issue by globally replacing `isstring(s)` with `exist('isstring', 'builtin') && isstring(s)`

**Comment by eywalker** [comment]
Sounds good, thanks. I think it is good to keep at least 2 years of backward compatibility, and in general try to keep as much compatibility as possible. If a new feature arise and if we find it to be important enough, then we can consider dropping support for older versions.

**Comment by eywalker** [comment]
I'll close this issue when a PR with the fix is merged.

**Comment by eywalker** [comment]
Fix incorporated into release `v3.0.0` via #83
