### ISSUE TITLE
Table preview throws error when a string field is empty.

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-matlab#81]
This traces to the fact that MATLAB has a bug in the following call

```matlab
struct2table(struct('a', 1, ,'b', ''))
```

To fix, replace empty strings '' with a single space ' ' before display.

**Comment by eywalker** [comment]
Fixed with #82

**Comment by eywalker** [comment]
Will close this upon merging `development` branch into `master`.

**Comment by eywalker** [comment]
Fix merged into `master` with #83

**Comment by dimitri-yatsenko** [comment]
Mathworks response to my bug report:

    I am writing in reference to your Technical Support Case #02527690 regarding 'struct2table bug'. 
 
    I understand that you get the below error after executing the command: struct2table(struct('a', 1, 'b', ''))

    Error using table.fromScalarStruct (line 316)
    Fields in a scalar structure must have the same number of rows.

    Error in struct2table (line 65)
        t = table.fromScalarStruct(s);

    In order to get rid of this error, use the below command,
    >> struct2table(struct('a', 1, 'b', ''),'AsArray',true)

    'AsArray' is 'false' by default which implies that the scalar struct must have same number of rows for each of its field.

    I hope this helps. I am closing this case now. Feel free to reply back to this email if you have any further concerns.

    Please preserve the Reference ID in further correspondence on this query. This allows our systems to automatically associate your reply to the appropriate Case. 

    If you have a new technical support question, please submit a new request here: 
    http://www.mathworks.com/support/servicerequests/create.html

Indeed their proposed solution seems to work. I will revert the change and use their solution.
