### ISSUE TITLE
Optionally suppress count display

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-matlab#85]
When working with large tables (e.g. a billion tuples), fetching is quick but getting the count may take a long time (e.g. 60 s).  This makes previously annoyingly slow.

I propose to add the configuration option to turn off the display of the total count of tuples from the preview. 

```
dj.set('displayCount', false)
```
It will be `true` by default.

**Comment by ixcat** [comment]
now will be via dj.config

**Comment by ixcat** [comment]
this is `display.tuple_count` in python; matlab would use `displayTupleCount`; should either change `displayCount` here or change to `display.count` in python for consistency
